[PHP]
engine=On
short_open_tag=Off
precision=14
output_buffering=4096
zlib.output_compression=Off
implicit_flush=Off
serialize_precision=-1
disable_functions=
disable_classes=
zend.enable_gc=On
expose_php=Off

max_execution_time=180
max_input_time=180
memory_limit=512M
post_max_size=100M
upload_max_filesize=100M
max_file_uploads=50

default_charset="UTF-8"
date.timezone=America/Guayaquil

extension_dir="C:\Users\Sebas2hVR\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"

extension=curl
extension=fileinfo
extension=gd
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=zip

[Session]
session.save_handler=files
session.use_strict_mode=0
session.use_cookies=1
session.use_only_cookies=1
session.name=PHPSESSID
session.auto_start=0

[opcache]
opcache.enable=0
